## NYXUS bar visualizer - cava config (raw ascii output for EWW)
[general]
framerate = 30
bars = 14
autosens = 1
sleep_timer = 3

[input]
method = pulse

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 7

[smoothing]
noise_reduction = 66
monstercat = 1
