background {
    monitor =
    path = ~/.config/hypr/wallpapers/nexus.jpg
    blur_passes = 3
    blur_size = 8
    color = rgba(1a1b26ff)
}

input-field {
    monitor =
    size = 300, 55
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true
    outer_color = rgba(7aa2f7ff)
    inner_color = rgba(1a1b26cc)
    font_color = rgba(c0caf5ff)
    fade_on_empty = false
    placeholder_text = <i>Enter password…</i>
    hide_input = false
    position = 0, -50
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    color = rgba(c0caf5ff)
    font_size = 90
    font_family = JetBrainsMono Nerd Font
    position = 0, 200
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +'%A, %d %B')"
    color = rgba(a9b1d6ff)
    font_size = 22
    font_family = JetBrainsMono Nerd Font
    position = 0, 100
    halign = center
    valign = center
}

label {
    monitor =
    text = NEXUS · $USER
    color = rgba(7aa2f7ff)
    font_size = 16
    font_family = JetBrainsMono Nerd Font
    position = 0, -140
    halign = center
    valign = center
}
